name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Run main workflow
        uses: ./.github/workflows/main.yml

      - name: Run code quality check
        uses: ./.github/workflows/codeql.yml

      - name: Merge PR
        if: success()
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Reject PR
        if: failure()
        run: |
          gh pr comment --body "Test cases are failed! Since I am closing this PR" "$PR_URL"
          gh pr close "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
